import {Component, OnInit} from "@angular/core";
import {ActivatedRoute, Params, /*Router*/} from "@angular/router";
import {ManagementServiceFacade} from "../services/management.service.facade";

export const CONCLUSION_PARAM = "conclusion";
export const MESSAGES_PARAM = "messages";


@Component({
    template: `
        <div class="main">
            <div class="main-header">
                <div>
                    <img src="icons/logo.png">
                    <h2>DE Management Console</h2>
                </div>
            </div>
            <div class="header">
                <h2 class="flah">DECISION RESULT</h2>
            </div>
            <div class="main-content">
                <h4>{{userMessage}}</h4>
                
            </div>
        </div>
    `,
    selector: 'alis-integration',
    styleUrls: ["./alis-integration.component.less"]
})
export class AlisIntegrationComponent implements OnInit{

    userMessage: string;
    constructor(private route: ActivatedRoute, private service: ManagementServiceFacade) {
    }

    ngOnInit(): void {
        this.service.isLocal$.subscribe(r => {
            if (r == null) return;

            this.route.queryParams.subscribe((params: Params) => {
                let conclusion = params[CONCLUSION_PARAM];
                this.userMessage = params[MESSAGES_PARAM];
                if (conclusion === 'Create Authorized Claim') {
                     this.prepareJsonAndCallAlis(this.getJsonForApprovedClaim);
                } else if (conclusion === 'Create Initial Notification Claim') {
                    this.prepareJsonAndCallAlis(this.getJsonForInitialNotificationClaim);
                }

                this.service.clearFlowInputs();
            });

        });
    }

    private prepareJsonAndCallAlis(getJsonFunc: Function){
        let clientId = parseInt(this.service.getFlowInputs().executionKeyValues.DecisionRootId);
        let policyId = parseInt(this.service.getFlowInputs().PolicyNumber);
        let json = getJsonFunc(clientId, policyId);
        this.service.callAlis(json);
    }

    private getJsonForApprovedClaim(clientId: number, policyNumber: number) {
        return {
            claimRequiredDocs: [
                {
                    "mustFlag": 1,
                    "requiredDocumentNo": 36,

                    "tProductClaimRequiredDoc": {
                        "validationCode": 2
                    },
                    "requestDate": "2018-01-01T00:00:00.000Z",
                    "receivedDate": "2018-01-01T00:00:00.000Z"
                },
                {
                    "mustFlag": 1,
                    "requiredDocumentNo": 38,

                    "tProductClaimRequiredDoc": {
                        "validationCode": 2
                    },
                    "requestDate": "2018-01-01T00:00:00.000Z",
                    "receivedDate": "2018-01-01T00:00:00.000Z"
                }
            ],
            "claimCovers": [
                {
                    "_DeleteEntity": null,
                    "managementData": null,
                    "primaryKey": null,
                    "closingEffecDate": null,
                    "closingRegDate": null,
                    "openingEffecDate": null,
                    "openingRegDate": null,
                    "closingRef": null,
                    "closingStatus": null,
                    "openingRef": null,
                    "openingStatus": null,
                    "policyNo": policyNumber,
                    "claimId": null,
                    "role": 10,
                    "coverNo": 6001,
                    "tCover": {
                        "_DeleteEntity": null,
                        "managementData": null,
                        "primaryKey": 264,
                        "effecDate": "1950-01-01T00:00:00.000Z",
                        "toEffecDate": "3000-01-01T00:00:00.000Z",
                        "className": "TCover",
                        "coverNo": 6001,
                        "ageAtFinalPrem": null,
                        "ageAtFinalPremSwitch": 0,
                        "ageAtStartOfExtension": null,
                        "ageAtTermOfCover": 75,
                        "ageAtTermOfCoverSwitch": 0,
                        "annualGrowthCode": 0,
                        "annualGrowthFormulaNo": null,
                        "appendix1": null,
                        "appendix2": null,
                        "baseCommForRateCalc": null,
                        "basePremGroup": null,
                        "benefitAmountFormulaNo": null,
                        "benefitCalcByFormulaFlag": 0,
                        "benefitPeriod": null,
                        "benefitPeriodSwitch": 0,
                        "branch": null,
                        "category": null,
                        "claimedViaHealthClaimFlag": null,
                        "clause1": null,
                        "clause2": null,
                        "commutedCode": 0,
                        "composedRiskCoverFlag": 0,
                        "contestablePeriodCalcBasis": 24,
                        "contestablePeriodCode": 1,
                        "coverBmp": null,
                        "coverIllustAccPremBalance": null,
                        "coverIllustCode": 1,
                        "coverName": "Critical Illness - Accelerated",
                        "coverTypeCompany": 10,
                        "coverTypeInfo": 3,
                        "coveringCompany": null,
                        "deferralPeriod": null,
                        "deferralPeriodSwitch": 0,
                        "earlyPayFlag": 0,
                        "effectiveDateMask": 0,
                        "entityKey": 0,
                        "excludeFromUwSaFlag": 0,
                        "extendedTermInsCoverFlag": 0,
                        "extensionPeriod": null,
                        "extensionPeriodSwitch": 0,
                        "finalMarketingDate": "2999-01-01T00:00:00.000Z",
                        "finalPremiumValuesCode": 0,
                        "floorCalcMethod": null,
                        "genderSwitch": 0,
                        "glUnderwritingGroup": 1,
                        "iasRiskGuaranteeFlag": 1,
                        "illustNonGteedFlag": 0,
                        "interestRate": null,
                        "interestRateSwitch": 0,
                        "isTemplateCover": null,
                        "lastUpdatedRegDate": "2016-02-03T00:00:00.000Z",
                        "lastUpdatedUserId": 230,
                        "linkedCover": null,
                        "linkedCoverType": null,
                        "livingBenefitType": 0,
                        "loanDetailsMask": 1,
                        "loanInterestType": 0,
                        "loanRepaymentMethod": 0,
                        "managingCompany": null,
                        "maturityValueCode": 0,
                        "maxEntryAge": 70,
                        "maxEscalationAge": null,
                        "minEntryAge": 19,
                        "minTermAgeAtCoverEnd": null,
                        "noOfInsuredLives": 1,
                        "occupationRequiredFlag": 0,
                        "paidUpAdditionFlag": 0,
                        "phiType": null,
                        "premIncreaseFlag": 0,
                        "premIncreaseFromYear": null,
                        "premIncreasePercentage": null,
                        "premIncreasePeriod": null,
                        "premIncreaseType": null,
                        "premiumTermMethod": null,
                        "pupSurrenderCode": null,
                        "rateForSumAssurd": 1000,
                        "rateInfluenceByCommFlag": 0,
                        "reducedPremPaytTerm": null,
                        "regDate": "2015-08-06T00:00:00.000Z",
                        "reinsAssignOrder": 1,
                        "relationToEndowment": null,
                        "saAccumulationMethod": 0,
                        "saForPremiumCalcCode": 1,
                        "saIncreaseFlag": 0,
                        "saIncreaseFromYear": null,
                        "saIncreasePercentage": null,
                        "saIncreasePeriod": null,
                        "saIncreaseType": null,
                        "saIndividCode": null,
                        "saSalaryLinkedCode": null,
                        "salaryRequiredFlag": 0,
                        "savingTypeForUnderwriting": 1,
                        "shortenedCoverName": "CI",
                        "smokerSwitch": 0,
                        "spPaytPeriod": null,
                        "spPaytPeriodSwitch": 0,
                        "splitDeferredFlag": 0,
                        "termDateCalcMethod": null,
                        "underwritingGroup": 1,
                        "underwritingGroupOccLoading": 1,
                        "useForChargeableEventFlag": 0,
                        "uwGroupForLetters": null,
                        "uwGroupForReinsurance": 1,
                        "variablePremiumCode": 2
                    },
                    "internalCoverNo": 2,
                    "coverCommencementDate": "2018-01-01T00:00:00.000Z",
                    "actualBenefitEffectiveDate": "2018-01-01T00:00:00.000Z",
                    "amountToBePaid": null,
                    "amountToBePaidBalance": null,
                    "benefitAmtOverrideUserId": null,
                    "benefitEffectiveDate": "2018-01-01T00:00:00.000Z",
                    "benefitGroup": 1,
                    "benefitRequest": null,
                    "benefitRequestType": 2,
                    "claimElapseDate": null,
                    "claimReviewDate": null,
                    "continuingClaimFlag": null,
                    "coverStatus": null,
                    "dateAtEndOfBenefit": "3000-01-01T00:00:00.000Z",
                    "description": null,
                    "finalAmount": 50000,
                    "instructionType": null,
                    "internalClaimId": null,
                    "manualAutoCode": null,
                    "manualReinsClaimAmountFlag": null,
                    "origEscFixedPerc": null,
                    "origEscIndexType": null,
                    "origEscMethod": null,
                    "originalAmount": 50000,
                    "originalBenefitType": null,
                    "reinsBenefitPaymentType": null,
                    "reinsClaimAmount": null,
                    "reference": null,
                    "saForCashSurrDecrements": null,
                    "sumAssured": 50000,
                    "sumAssuredClaimedPart": 50000,
                    "surrenderAmount": null,
                    "userId": null,
                    "reinsBenefitEffecDate": null,
                    "claimAmountEntryCode": 1,
                    "partialAmountEntryMethod": 2,
                    "amtToBePaidValidCode": 0,
                    "minAmtToBePaid": null,
                    "maxAmtToBePaid": null,
                    "claimedSaValidCode": 0,
                    "minClaimedSa": null,
                    "maxClaimedSa": null,
                    "periodicalPaymentAmountType": 0,
                    "coverBenefitEffecDateCode": 1,
                    "coverBenefitEffecdatePeriod": null,
                    "coverBenefitEffecDateMask": 0,
                    "deferralPeriodForPhi": 0,
                    "deferredPeriodUnitCode": null,
                    "coverDateAtEndOfTerm": "2038-01-01T00:00:00.000Z",
                    "policyStatusTermDate": "2038-01-01T00:00:00.000Z",
                    "benefitPaymentPeriod": 0,
                    "benefitPaymentPeriodType": 0,
                    "termDateByAge": null,
                    "minSAMessage": null,
                    "reinsEffecDatePeriod": null,
                    "reinsEffecDateCode": null,
                    "maxSAMessage": null,
                    "minAmountMessage": null,
                    "maxAmountMessage": null,
                    "benefitPayCodeUnitCode": null,
                    "deferredPeriodWaiveFlag": 0,
                    "benefitPaymentPeriodMethod": 0,
                    "benefitPaymentEndDateMethod": 0,
                    "medicalItems": null,
                    "claimCoverConn": {
                        "_DeleteEntity": null,
                        "managementData": null,
                        "primaryKey": 2310,
                        "className": "TClaimCoverConn",
                        "claimType": 171,
                        "coverNo": 6001,
                        "actualBenefitEffecDateMask": null,
                        "amtToBePaidValidCode": 0,
                        "benefitCalculationCode": 2,
                        "benefitGroup": {
                            "_DeleteEntity": null,
                            "managementData": null,
                            "primaryKey": 1,
                            "className": "TBenefitGroup",
                            "benefitGroup": 1,
                            "benefitGroupShortName": "Lump Sum / Income",
                            "benefitGroupName": "Lump Sum / Income",
                            "benefitMainGroup": 1,
                            "balanceType": 0,
                            "lastUpdatedUserId": 600,
                            "lastUpdatedRegDate": "2007-04-04T00:00:00.000Z",
                            "dfltAnnuityRegime": 0,
                            "dfltTfcDeductionPriority": 0,
                            "dfltAnnuityParametersMask": 3,
                            "dfltAnnuityParametersFormat": null,
                            "groupForInfo": 0,
                            "allowNegativeValueFlag": 0,
                            "claimAdHocSourceFlag": 0,
                            "entityKey": 0
                        },
                        "benefitRequestTypesCode": 3,
                        "benefitTypeConversionCode": 0,
                        "claimAmountByPeriodFlag": 0,
                        "claimAmountEntryCode": 1,
                        "claimCoverConnectionType": 2,
                        "claimCoverPremType": null,
                        "claimPayStatChngDateCode": 1,
                        "claimPayStatusChangeFlag": 1,
                        "claimPaymentStatus": 87,
                        "claimedSaValidCode": 0,
                        "coverBenefitEffecDateCode": 1,
                        "coverBenefitEffecDateMask": 0,
                        "coverBenefitEffecdatePeriod": null,
                        "coverFundBenefitFlag": 0,
                        "coverStatusForSaReduction": null,
                        "coverUpdateCode": 8,
                        "deferredPeriodWaiveFlag": 0,
                        "essentialCoverFlag": 1,
                        "fullDetStatChngDateCode": null,
                        "fullDetailStatusChangeFlag": 0,
                        "fullDetailsStatus": null,
                        "incomeClaimElapseCode": null,
                        "incomeClaimElapsePeriod": null,
                        "incomeClaimReviewCode": null,
                        "incomeClaimReviewDateMask": null,
                        "incomeClaimReviewPeriod": null,
                        "initNotifStatChngDateCode": null,
                        "initNotifyStatus": null,
                        "initNotifyStatusChangeFlag": 0,
                        "lastUpdatedRegDate": null,
                        "lastUpdatedUserId": null,
                        "maxAmtToBePaid": 999999.99,
                        "maxAmtToBePaidCompliance": 1934,
                        "maxClaimedSa": 250000,
                        "maxClaimedSaCompliance": 1934,
                        "minAmtToBePaid": 5000,
                        "minAmtToBePaidCompliance": 972,
                        "minClaimedSa": 5000,
                        "minClaimedSaCompliance": null,
                        "partialAmountDefaultCode": null,
                        "partialAmountDefaultPerc": null,
                        "partialAmountEntryMethod": 2,
                        "periodicalPaymentAmountType": 0,
                        "priority": null,
                        "pupCoverStatusSaReduction": null,
                        "reinsClaimMovementType": null,
                        "reinsuranceClaimCalcCode": null,
                        "replacingCoverNo": null,
                        "saReductionCoverStatus": 12,
                        "saReductionPupCoverStatus": null,
                        "surrenderClaimCode": null,
                        "transitionDestinyCover": null,
                        "transitionType": null,
                        "waitingPeriodLimitInMonths": null,
                        "tClaimType": {
                            "_DeleteEntity": null,
                            "managementData": null,
                            "primaryKey": 160,
                            "className": "TClaimType",
                            "claimType": 171,
                            "activityCode": 9006,
                            "allowEscalFlag": null,
                            "approvalBeforePaymentFlag": 0,
                            "associatedAutoClaimType": 0,
                            "autoClaimBehavior": 0,
                            "autoClaimPayApprovalFlag": 0,
                            "automaticClaimGroup": null,
                            "benefitOverrideCheckboxFlag": 0,
                            "claimCleanupFlag": 0,
                            "claimTypeGroup": 16,
                            "claimTypeGroupGeneralCode": {
                                "_DeleteEntity": null,
                                "managementData": null,
                                "primaryKey": 1682,
                                "className": "TGeneralCode",
                                "codeType": 810,
                                "codeValue": 16,
                                "codeGroup": null,
                                "codeName": "Accelerated Death",
                                "codeShortName": "Accelerated Death",
                                "codeValueFloat": 0,
                                "dddwDefault": 0,
                                "dddwFlag": 0,
                                "entityKey": 0,
                                "lastUpdatedRegDate": "2009-01-08T00:00:00.000Z",
                                "lastUpdatedUserId": 230,
                                "userDefinedFlag": 0,
                                "displayFlag": 1
                            },
                            "claimTypeMainGroup": 1,
                            "claimTypeName": "Accelerated Death - Critical Illness",
                            "clientClaimTypeGroup": 0,
                            "commDateNextDayCloseFlag": 1,
                            "coverSplitAllowFlag": null,
                            "dependentClaimFlag": 0,
                            "entityKey": 0,
                            "forbidClaimCashExistFlag": 0,
                            "lastUpdatedRegDate": null,
                            "lastUpdatedUserId": null,
                            "mainClaimForDependentClaim": 0,
                            "paidUpClaimCode": null,
                            "paymentCalendarDayFlag": 0,
                            "postClosePrevDayRetrieve": 0,
                            "sarValuationFlag": 0,
                            "valuationFlag": 0
                        },
                        "reinsEffecDatePeriod": null,
                        "reinsEffecDateCode": null
                    }
                }
            ],
            "claimFundSurrender": [],
            "claimAdditionalAmount": [],
            "claimItem": [],
            "claimRefund": [],
            "paymentOrders": [],
            "claimWaiver": [],
            "claimBeneficiaries": [],
            "taxEvents": [],
            "policyNo": policyNumber,
            "claimType": 171,
            "claimSubType": 10,
            "claimNotificationDate": "2018-01-01T00:00:00.000Z",
            "openingEffecDate": "2018-01-01T00:00:00.000Z",
            "claimPriceDate": "2018-01-01T00:00:00.000Z",
            "currentStatus": 15,
            "pendingReasonCode": 0,
            "approvalReasonCode": 5,
            "cancellationReasonCode": 0,
            "declineReasonCode": 0,
            "clientId": clientId,
            "initialNoteReasonCode": 0,
            "primaryMedicalReason": 1
        };
    }

    private getJsonForInitialNotificationClaim(clientId: number, policyId: number) {
        return {
            "claimRequiredDocs": [
                {
                    "mustFlag": 1,
                    "requiredDocumentNo": 36,
                    "tProductClaimRequiredDoc": {
                        "validationCode": 2
                    },
                    "requestDate": "2018-12-11T00:00:00.000Z",
                    "receivedDate": "2018-12-11T00:00:00.000Z"
                },
                {
                    "mustFlag": 1,
                    "requiredDocumentNo": 38,
                    "tProductClaimRequiredDoc": {
                        "validationCode": 2
                    },
                    "receivedDate": "2018-12-11T00:00:00.000Z",
                    "requestDate": "2018-12-11T00:00:00.000Z"
                }
            ],
            "claimCovers": [
                {
                    "_DeleteEntity": null,
                    "managementData": null,
                    "primaryKey": null,
                    "closingEffecDate": null,
                    "closingRegDate": null,
                    "openingEffecDate": null,
                    "openingRegDate": null,
                    "closingRef": null,
                    "closingStatus": null,
                    "openingRef": null,
                    "openingStatus": null,
                    "policyNo": policyId,
                    "claimId": null,
                    "role": 10,
                    "coverNo": 6001,
                    "tCover": {
                        "_DeleteEntity": null,
                        "managementData": null,
                        "primaryKey": 264,
                        "effecDate": "1950-01-01T00:00:00.000Z",
                        "toEffecDate": "3000-01-01T00:00:00.000Z",
                        "className": "TCover",
                        "coverNo": 6001,
                        "ageAtFinalPrem": null,
                        "ageAtFinalPremSwitch": 0,
                        "ageAtStartOfExtension": null,
                        "ageAtTermOfCover": 75,
                        "ageAtTermOfCoverSwitch": 0,
                        "annualGrowthCode": 0,
                        "annualGrowthFormulaNo": null,
                        "appendix1": null,
                        "appendix2": null,
                        "baseCommForRateCalc": null,
                        "basePremGroup": null,
                        "benefitAmountFormulaNo": null,
                        "benefitCalcByFormulaFlag": 0,
                        "benefitPeriod": null,
                        "benefitPeriodSwitch": 0,
                        "branch": null,
                        "category": null,
                        "claimedViaHealthClaimFlag": null,
                        "clause1": null,
                        "clause2": null,
                        "commutedCode": 0,
                        "composedRiskCoverFlag": 0,
                        "contestablePeriodCalcBasis": 24,
                        "contestablePeriodCode": 1,
                        "coverBmp": null,
                        "coverIllustAccPremBalance": null,
                        "coverIllustCode": 1,
                        "coverName": "Critical Illness - Accelerated",
                        "coverTypeCompany": 10,
                        "coverTypeInfo": 3,
                        "coveringCompany": null,
                        "deferralPeriod": null,
                        "deferralPeriodSwitch": 0,
                        "earlyPayFlag": 0,
                        "effectiveDateMask": 0,
                        "entityKey": 0,
                        "excludeFromUwSaFlag": 0,
                        "extendedTermInsCoverFlag": 0,
                        "extensionPeriod": null,
                        "extensionPeriodSwitch": 0,
                        "finalMarketingDate": "2999-01-01T00:00:00.000Z",
                        "finalPremiumValuesCode": 0,
                        "floorCalcMethod": null,
                        "genderSwitch": 0,
                        "glUnderwritingGroup": 1,
                        "iasRiskGuaranteeFlag": 1,
                        "illustNonGteedFlag": 0,
                        "interestRate": null,
                        "interestRateSwitch": 0,
                        "isTemplateCover": null,
                        "lastUpdatedRegDate": "2016-02-03T00:00:00.000Z",
                        "lastUpdatedUserId": 230,
                        "linkedCover": null,
                        "linkedCoverType": null,
                        "livingBenefitType": 0,
                        "loanDetailsMask": 1,
                        "loanInterestType": 0,
                        "loanRepaymentMethod": 0,
                        "managingCompany": null,
                        "maturityValueCode": 0,
                        "maxEntryAge": 70,
                        "maxEscalationAge": null,
                        "minEntryAge": 19,
                        "minTermAgeAtCoverEnd": null,
                        "noOfInsuredLives": 1,
                        "occupationRequiredFlag": 0,
                        "paidUpAdditionFlag": 0,
                        "phiType": null,
                        "premIncreaseFlag": 0,
                        "premIncreaseFromYear": null,
                        "premIncreasePercentage": null,
                        "premIncreasePeriod": null,
                        "premIncreaseType": null,
                        "premiumTermMethod": null,
                        "pupSurrenderCode": null,
                        "rateForSumAssurd": 1000,
                        "rateInfluenceByCommFlag": 0,
                        "reducedPremPaytTerm": null,
                        "regDate": "2015-08-06T00:00:00.000Z",
                        "reinsAssignOrder": 1,
                        "relationToEndowment": null,
                        "saAccumulationMethod": 0,
                        "saForPremiumCalcCode": 1,
                        "saIncreaseFlag": 0,
                        "saIncreaseFromYear": null,
                        "saIncreasePercentage": null,
                        "saIncreasePeriod": null,
                        "saIncreaseType": null,
                        "saIndividCode": null,
                        "saSalaryLinkedCode": null,
                        "salaryRequiredFlag": 0,
                        "savingTypeForUnderwriting": 1,
                        "shortenedCoverName": "CI",
                        "smokerSwitch": 0,
                        "spPaytPeriod": null,
                        "spPaytPeriodSwitch": 0,
                        "splitDeferredFlag": 0,
                        "termDateCalcMethod": null,
                        "underwritingGroup": 1,
                        "underwritingGroupOccLoading": 1,
                        "useForChargeableEventFlag": 0,
                        "uwGroupForLetters": null,
                        "uwGroupForReinsurance": 1,
                        "variablePremiumCode": 2
                    },
                    "internalCoverNo": 2,
                    "coverCommencementDate": "2018-01-01T00:00:00.000Z",
                    "actualBenefitEffectiveDate": "2018-12-11T00:00:00.000Z",
                    "amountToBePaid": null,
                    "amountToBePaidBalance": null,
                    "benefitAmtOverrideUserId": null,
                    "benefitEffectiveDate": "2018-12-11T00:00:00.000Z",
                    "benefitGroup": 1,
                    "benefitRequest": null,
                    "benefitRequestType": 2,
                    "claimElapseDate": null,
                    "claimReviewDate": null,
                    "continuingClaimFlag": null,
                    "coverStatus": null,
                    "dateAtEndOfBenefit": "3000-01-01T00:00:00.000Z",
                    "description": null,
                    "finalAmount": 50000,
                    "instructionType": null,
                    "internalClaimId": null,
                    "manualAutoCode": null,
                    "manualReinsClaimAmountFlag": null,
                    "origEscFixedPerc": null,
                    "origEscIndexType": null,
                    "origEscMethod": null,
                    "originalAmount": 50000,
                    "originalBenefitType": null,
                    "reinsBenefitPaymentType": null,
                    "reinsClaimAmount": null,
                    "reference": null,
                    "saForCashSurrDecrements": null,
                    "sumAssured": 50000,
                    "sumAssuredClaimedPart": 50000,
                    "surrenderAmount": null,
                    "userId": null,
                    "reinsBenefitEffecDate": null,
                    "claimAmountEntryCode": 1,
                    "partialAmountEntryMethod": 2,
                    "amtToBePaidValidCode": 0,
                    "minAmtToBePaid": null,
                    "maxAmtToBePaid": null,
                    "claimedSaValidCode": 0,
                    "minClaimedSa": null,
                    "maxClaimedSa": null,
                    "periodicalPaymentAmountType": 0,
                    "coverBenefitEffecDateCode": 1,
                    "coverBenefitEffecdatePeriod": null,
                    "coverBenefitEffecDateMask": 0,
                    "deferralPeriodForPhi": 0,
                    "deferredPeriodUnitCode": null,
                    "coverDateAtEndOfTerm": "2038-01-01T00:00:00.000Z",
                    "policyStatusTermDate": "2038-01-01T00:00:00.000Z",
                    "benefitPaymentPeriod": 0,
                    "benefitPaymentPeriodType": 0,
                    "termDateByAge": null,
                    "minSAMessage": null,
                    "reinsEffecDatePeriod": null,
                    "reinsEffecDateCode": null,
                    "maxSAMessage": null,
                    "minAmountMessage": null,
                    "maxAmountMessage": null,
                    "benefitPayCodeUnitCode": null,
                    "deferredPeriodWaiveFlag": 0,
                    "benefitPaymentPeriodMethod": 0,
                    "benefitPaymentEndDateMethod": 0,
                    "medicalItems": null,
                    "claimCoverConn": {
                        "_DeleteEntity": null,
                        "managementData": null,
                        "primaryKey": 2310,
                        "className": "TClaimCoverConn",
                        "claimType": 171,
                        "coverNo": 6001,
                        "actualBenefitEffecDateMask": null,
                        "amtToBePaidValidCode": 0,
                        "benefitCalculationCode": 2,
                        "benefitGroup": {
                            "_DeleteEntity": null,
                            "managementData": null,
                            "primaryKey": 1,
                            "className": "TBenefitGroup",
                            "benefitGroup": 1,
                            "benefitGroupShortName": "Lump Sum / Income",
                            "benefitGroupName": "Lump Sum / Income",
                            "benefitMainGroup": 1,
                            "balanceType": 0,
                            "lastUpdatedUserId": 600,
                            "lastUpdatedRegDate": "2007-04-04T00:00:00.000Z",
                            "dfltAnnuityRegime": 0,
                            "dfltTfcDeductionPriority": 0,
                            "dfltAnnuityParametersMask": 3,
                            "dfltAnnuityParametersFormat": null,
                            "groupForInfo": 0,
                            "allowNegativeValueFlag": 0,
                            "claimAdHocSourceFlag": 0,
                            "entityKey": 0
                        },
                        "benefitRequestTypesCode": 3,
                        "benefitTypeConversionCode": 0,
                        "claimAmountByPeriodFlag": 0,
                        "claimAmountEntryCode": 1,
                        "claimCoverConnectionType": 2,
                        "claimCoverPremType": null,
                        "claimPayStatChngDateCode": 1,
                        "claimPayStatusChangeFlag": 1,
                        "claimPaymentStatus": 87,
                        "claimedSaValidCode": 0,
                        "coverBenefitEffecDateCode": 1,
                        "coverBenefitEffecDateMask": 0,
                        "coverBenefitEffecdatePeriod": null,
                        "coverFundBenefitFlag": 0,
                        "coverStatusForSaReduction": null,
                        "coverUpdateCode": 8,
                        "deferredPeriodWaiveFlag": 0,
                        "essentialCoverFlag": 1,
                        "fullDetStatChngDateCode": null,
                        "fullDetailStatusChangeFlag": 0,
                        "fullDetailsStatus": null,
                        "incomeClaimElapseCode": null,
                        "incomeClaimElapsePeriod": null,
                        "incomeClaimReviewCode": null,
                        "incomeClaimReviewDateMask": null,
                        "incomeClaimReviewPeriod": null,
                        "initNotifStatChngDateCode": null,
                        "initNotifyStatus": null,
                        "initNotifyStatusChangeFlag": 0,
                        "lastUpdatedRegDate": null,
                        "lastUpdatedUserId": null,
                        "maxAmtToBePaid": 999999.99,
                        "maxAmtToBePaidCompliance": 1934,
                        "maxClaimedSa": 250000,
                        "maxClaimedSaCompliance": 1934,
                        "minAmtToBePaid": 5000,
                        "minAmtToBePaidCompliance": 972,
                        "minClaimedSa": 5000,
                        "minClaimedSaCompliance": null,
                        "partialAmountDefaultCode": null,
                        "partialAmountDefaultPerc": null,
                        "partialAmountEntryMethod": 2,
                        "periodicalPaymentAmountType": 0,
                        "priority": null,
                        "pupCoverStatusSaReduction": null,
                        "reinsClaimMovementType": null,
                        "reinsuranceClaimCalcCode": null,
                        "replacingCoverNo": null,
                        "saReductionCoverStatus": 12,
                        "saReductionPupCoverStatus": null,
                        "surrenderClaimCode": null,
                        "transitionDestinyCover": null,
                        "transitionType": null,
                        "waitingPeriodLimitInMonths": null,
                        "tClaimType": {
                            "_DeleteEntity": null,
                            "managementData": null,
                            "primaryKey": 160,
                            "className": "TClaimType",
                            "claimType": 171,
                            "activityCode": 9006,
                            "allowEscalFlag": null,
                            "approvalBeforePaymentFlag": 0,
                            "associatedAutoClaimType": 0,
                            "autoClaimBehavior": 0,
                            "autoClaimPayApprovalFlag": 0,
                            "automaticClaimGroup": null,
                            "benefitOverrideCheckboxFlag": 0,
                            "claimCleanupFlag": 0,
                            "claimTypeGroup": 16,
                            "claimTypeGroupGeneralCode": {
                                "_DeleteEntity": null,
                                "managementData": null,
                                "primaryKey": 1682,
                                "className": "TGeneralCode",
                                "codeType": 810,
                                "codeValue": 16,
                                "codeGroup": null,
                                "codeName": "Accelerated Death",
                                "codeShortName": "Accelerated Death",
                                "codeValueFloat": 0,
                                "dddwDefault": 0,
                                "dddwFlag": 0,
                                "entityKey": 0,
                                "lastUpdatedRegDate": "2009-01-08T00:00:00.000Z",
                                "lastUpdatedUserId": 230,
                                "userDefinedFlag": 0,
                                "displayFlag": 1
                            },
                            "claimTypeMainGroup": 1,
                            "claimTypeName": "Accelerated Death - Critical Illness",
                            "clientClaimTypeGroup": 0,
                            "commDateNextDayCloseFlag": 1,
                            "coverSplitAllowFlag": null,
                            "dependentClaimFlag": 0,
                            "entityKey": 0,
                            "forbidClaimCashExistFlag": 0,
                            "lastUpdatedRegDate": null,
                            "lastUpdatedUserId": null,
                            "mainClaimForDependentClaim": 0,
                            "paidUpClaimCode": null,
                            "paymentCalendarDayFlag": 0,
                            "postClosePrevDayRetrieve": 0,
                            "sarValuationFlag": 0,
                            "valuationFlag": 0
                        },
                        "reinsEffecDatePeriod": null,
                        "reinsEffecDateCode": null
                    }
                }
            ],
            "claimFundSurrender": [],
            "claimAdditionalAmount": [],
            "claimItem": [],
            "claimRefund": [],
            "paymentOrders": [],
            "claimWaiver": [],
            "claimBeneficiaries": [],
            "taxEvents": [],
            "policyNo": policyId,
            "originalOpeningRegDate": "2018-12-11T00:00:00.000Z",
            "claimType": 171,
            "claimSubType": 10,
            "claimNotificationDate": "2018-12-11T00:00:00.000Z",
            "openingEffecDate": "2018-12-11T00:00:00.000Z",
            "claimPriceDate": "2018-12-11T00:00:00.000Z",
            "currentStatus": 10,
            "pendingReasonCode": 0,
            "approvalReasonCode": 0,
            "cancellationReasonCode": 0,
            "declineReasonCode": 0,
            "clientId": clientId,
            "primaryMedicalReason": 3,
            "totalPayable": null,
            "initialNoteReasonCode": 1,
            "requestType": 1
        }
    }
}

